import express, { Request, Response } from 'express';
import { db } from '../db/memoryDB'; // Ensure removal if unused
import AccountsReceivable from '../models/AccountsReceivable';
import Invoice from '../models/Invoice';
import Project from '../models/Project';
import Customer from '../models/Customer';
import mongoose from 'mongoose';

const router = express.Router();

/**
 * GET /api/accounts-receivable
 * AR 목록 조회
 */
router.get('/', async (req: Request, res: Response) => {
  try {
    const { customerId, projectId, invoiceId, status, paymentStatus, overdue } = req.query;

    let query: any = {};
    if (customerId) query.customer = customerId;
    if (projectId) query.project = projectId;
    if (invoiceId) query.invoice = invoiceId;
    if (status) query.status = status;
    if (paymentStatus) query.paymentStatus = paymentStatus;

    // 연체 필터
    if (overdue === 'true') {
      query.$or = [
        { status: 'overdue' },
        {
          dueDate: { $lt: new Date() },
          paymentStatus: { $ne: 'paid' }
        }
      ];
    }

    const ars = await AccountsReceivable.find(query)
      .populate('customer', 'name company')
      .populate('project', 'projectCode projectName')
      .populate('invoice', 'invoiceNumber')
      .sort({ dueDate: 1 });

    res.json(ars);
  } catch (error: any) {
    res.status(500).json({ message: error.message });
  }
});

/**
 * GET /api/accounts-receivable/:id
 * AR 상세 조회
 */
router.get('/:id', async (req: Request, res: Response) => {
  try {
    const ar = await AccountsReceivable.findById(req.params.id)
      .populate('customer', 'name company')
      .populate('project', 'projectCode projectName')
      .populate('invoice', 'invoiceNumber');

    if (!ar) {
      return res.status(404).json({ message: 'AR을 찾을 수 없습니다' });
    }

    res.json(ar);
  } catch (error: any) {
    res.status(500).json({ message: error.message });
  }
});

/**
 * POST /api/accounts-receivable
 * AR 생성 (Invoice에서 자동 생성 또는 수동 생성)
 */
router.post('/', async (req: Request, res: Response) => {
  try {
    const { invoiceId, ...arData } = req.body;

    // Invoice에서 AR 생성
    if (invoiceId) {
      const invoice = await Invoice.findById(invoiceId);
      if (!invoice) {
        return res.status(404).json({ message: 'Invoice를 찾을 수 없습니다' });
      }

      // 이미 AR이 생성되었는지 확인
      const existingAR = await AccountsReceivable.findOne({ invoice: invoiceId });
      if (existingAR) {
        return res.status(400).json({ message: '이 Invoice에 대한 AR이 이미 존재합니다' });
      }

      // AR 생성
      const ar = new AccountsReceivable({
        // arNumber generated by pre-save
        invoice: invoiceId,
        customer: invoice.customer,
        project: invoice.project,
        invoiceNumber: invoice.invoiceNumber,
        invoiceDate: invoice.invoiceDate,
        dueDate: invoice.dueDate,
        subtotal: invoice.subtotal,
        tax: invoice.tax,
        discount: invoice.discount || 0,
        totalAmount: invoice.totalAmount,
        receivedAmount: 0,
        // remainingAmount calculated by pre-save
        // status calculated by pre-save
        currency: invoice.currency,
        receipts: [],
        createdBy: invoice.createdBy, // Assuming createdBy exists on invoice
      });

      await ar.save();

      // Invoice 상태 업데이트
      invoice.paymentStatus = 'pending';
      await invoice.save();

      return res.status(201).json(ar);
    }

    // 수동 AR 생성
    const ar = new AccountsReceivable({
      ...arData,
      // remainingAmount, status handled by pre-save
      receipts: arData.receipts || [],
    });

    await ar.save();
    res.status(201).json(ar);
  } catch (error: any) {
    res.status(500).json({ message: error.message });
  }
});

/**
 * POST /api/accounts-receivable/:id/receive
 * 수금 처리
 */
router.post('/:id/receive', async (req: Request, res: Response) => {
  try {
    const { amount, receiptDate, paymentMethod, referenceNumber, bankAccount, notes, userId } = req.body;

    if (!amount || amount <= 0) {
      return res.status(400).json({ message: '수금 금액을 입력하세요' });
    }

    const ar = await AccountsReceivable.findById(req.params.id);
    if (!ar) {
      return res.status(404).json({ message: 'AR을 찾을 수 없습니다' });
    }

    // 수금 내역 추가
    ar.receipts.push({
      receiptDate: receiptDate ? new Date(receiptDate) : new Date(),
      amount,
      paymentMethod: paymentMethod || 'bank_transfer',
      referenceNumber,
      bankAccount,
      notes,
      receivedBy: userId ? new mongoose.Types.ObjectId(userId) : undefined,
    });

    ar.receivedAmount = (ar.receivedAmount || 0) + amount;

    // Status and remainingAmount updated by pre-save hook
    await ar.save();

    // Invoice 상태도 업데이트 (Fixing Type Mismatch)
    if (ar.invoice) {
      const invoice = await Invoice.findById(ar.invoice);
      if (invoice) {
        // Map AR 'unpaid' to Invoice 'pending'
        let invoicePaymentStatus: any = ar.paymentStatus;
        if (ar.paymentStatus === 'unpaid') {
          invoicePaymentStatus = 'pending';
        }
        invoice.paymentStatus = invoicePaymentStatus;

        if (ar.paymentStatus === 'paid') {
          invoice.status = 'paid';
          invoice.paidDate = new Date();
        }
        await invoice.save();
      }
    }

    res.json(ar);
  } catch (error: any) {
    res.status(500).json({ message: error.message });
  }
});

/**
 * GET /api/accounts-receivable/dashboard/stats
 * AR 대시보드 통계
 */
router.get('/dashboard/stats', async (req: Request, res: Response) => {
  try {
    const [statsResult] = await AccountsReceivable.aggregate([
      {
        $group: {
          _id: null,
          totalAR: { $sum: '$totalAmount' },
          totalReceived: { $sum: '$receivedAmount' },
          totalRemaining: { $sum: '$remainingAmount' }
        }
      }
    ]);
    const { totalAR = 0, totalReceived = 0, totalRemaining = 0 } = statsResult || {};

    const overdueResult = await AccountsReceivable.aggregate([
      {
        $match: {
          dueDate: { $lt: new Date() },
          paymentStatus: { $ne: 'paid' }
        }
      },
      {
        $group: {
          _id: null,
          count: { $sum: 1 },
          amount: { $sum: '$remainingAmount' }
        }
      }
    ]);
    const overdue = overdueResult.length > 0 ? { count: overdueResult[0].count, amount: overdueResult[0].amount } : { count: 0, amount: 0 };

    const now = new Date();
    const thisMonthStart = new Date(now.getFullYear(), now.getMonth(), 1);
    const thisMonthEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0);

    const dueThisMonthResult = await AccountsReceivable.aggregate([
      {
        $match: {
          dueDate: { $gte: thisMonthStart, $lte: thisMonthEnd },
          paymentStatus: { $ne: 'paid' }
        }
      },
      {
        $group: {
          _id: null,
          count: { $sum: 1 },
          amount: { $sum: '$remainingAmount' }
        }
      }
    ]);
    const dueThisMonth = dueThisMonthResult.length > 0 ? { count: dueThisMonthResult[0].count, amount: dueThisMonthResult[0].amount } : { count: 0, amount: 0 };

    res.json({
      totalAR,
      totalReceived,
      totalRemaining,
      overdueCount: overdue.count,
      overdueAmount: overdue.amount,
      dueThisMonthCount: dueThisMonth.count,
      dueThisMonthAmount: dueThisMonth.amount,
    });
  } catch (error: any) {
    res.status(500).json({ message: error.message });
  }
});

/**
 * GET /api/accounts-receivable/customer/:customerId
 * 고객별 AR 현황
 */
router.get('/customer/:customerId', async (req: Request, res: Response) => {
  try {
    const ars = await AccountsReceivable.find({ customer: req.params.customerId })
      .populate('project', 'projectCode projectName');

    const total = ars.reduce((sum: number, ar: any) => sum + (ar.totalAmount || 0), 0);
    const received = ars.reduce((sum: number, ar: any) => sum + (ar.receivedAmount || 0), 0);
    const remaining = ars.reduce((sum: number, ar: any) => sum + (ar.remainingAmount || 0), 0);

    res.json({
      customerId: req.params.customerId,
      totalARs: ars.length,
      totalAmount: total,
      receivedAmount: received,
      remainingAmount: remaining,
      ars,
    });
  } catch (error: any) {
    res.status(500).json({ message: error.message });
  }
});

/**
 * PUT /api/accounts-receivable/:id
 * AR 수정
 */
router.put('/:id', async (req: Request, res: Response) => {
  try {
    const arForSave = await AccountsReceivable.findById(req.params.id);
    if (!arForSave) return res.status(404).json({ message: 'AR not found' });

    Object.assign(arForSave, req.body);
    await arForSave.save(); // updates status via hooks

    res.json(arForSave);
  } catch (error: any) {
    res.status(500).json({ message: error.message });
  }
});

/**
 * DELETE /api/accounts-receivable/:id
 * AR 삭제
 */
router.delete('/:id', async (req: Request, res: Response) => {
  try {
    const deleted = await AccountsReceivable.findByIdAndDelete(req.params.id);
    if (!deleted) {
      return res.status(404).json({ message: 'AR을 찾을 수 없습니다' });
    }
    res.json({ message: 'AR이 삭제되었습니다' });
  } catch (error: any) {
    res.status(500).json({ message: error.message });
  }
});

export default router;
